### PR TITLE
Fix DASM and Merlin, add Asar, improve cc65

### PR DESCRIPTION
**Pull request by georgjz**
* Added a new grammar to support [Asar Assembler](https://github.com/RPGHacker/asar)
    * SPC700 and SuperFX opcodes are missing yet. I plan to extract them from the SNES cc65 grammar
* DASM and Merlin should work now
* cc65
    * Added some missing commands and constants
    * Changed some scopes to improve readability
    * Added a new grammar for the linker config files ld65 uses
    * Updated the link in README.md
* Fixed hex numbers with a trailing h
* Add missing commands to WDC tools

### CODE REVIEW

**Review by MatthewCallis — APPROVED** [review]

**Comment by MatthewCallis** [comment]
@georgjz did you want to wait to add the SPC700 and SuperFX opcodes before merging?

**Comment by MatthewCallis** [comment]
@georgjz I've also added you as a collaborator on the project!

**Comment by georgjz** [comment]
@MatthewCallis Thank you for adding me! I already started doing it, I'll update and merge it as soon I finish it.

**Comment by georgjz** [comment]
I'm sorry for my late reply, I finally got around playing Breath of the Wild(it's  f:heart::heart::heart:ing amazing) which distracted me a lot. I added the SPC-700 and SuperFX opcodes.

**Pull request merged**
